apps/storm/urls.py
from django.conf.urls import url, include
from .views import (IndexView, DetailView, MessageView, AboutView, DonateView, ExchangeView, ProjectView, QuestionView, MySearchView, LoveView, LinkView)

urlpatterns = [
    # 首页
    url(r'^$', IndexView.as_view(template_name='index.html'), name='index'),  # 主页，自然排序
    url(r'^link/$', LinkView, name='link'),     # 申请友情链接
    url(r'^category/message/$', MessageView, name='message'),   # 给我留言
    url(r'^category/about/$', AboutView, name='about'), # 关于作者
    url(r'^category/donate/$', DonateView, name='donate'),  # 打赏作者
    url(r'^category/exchange/$', ExchangeView, name='exchange'),    # 技术交流
    url(r'^category/project/$', ProjectView, name='project'),   # 项目合作
    url(r'^category/question/$', QuestionView, name='question'),    # 提问交流
    # 分类页面
    url(r'^category/(?P<bigslug>.*)/(?P<slug>.*)', IndexView.as_view(template_name='content.html'), name='category'),
    # 归档页面
    url(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),
    # 标签页面
    url(r'^tag/(?P<tag>.*)/$', IndexView.as_view(template_name='content.html'), name='tag'),
    # 文章详情页面
    url(r'^article/(?P<slug>.*)/$', DetailView.as_view(), name='article'),
    # 全文搜索
    url(r'^search/$', MySearchView.as_view(), name='search'),
    # 喜欢
    url(r'^love/$', LoveView, name='love'),
    # 富文本编辑器接收文件
    url(r'ckeditor/', include('ckeditor_uploader.urls'))
]

apps/user/urls.py
from django.conf.urls import url
from rest_framework.documentation import include_docs_urls
# from .views import login_view, logout_view, register_view, profile_view, change_profile_view
from .views import *

urlpatterns = [
    url(r'^login/$', login_view, name='login'), # 用户登录
    url(r'^logout', logout_view, name='logout'),    # 用户退出
    url(r'^register/$', register_view, name='register'),    # 用户注册
    url(r'^profile/$', profile_view, name='profile'),   # 用户查看资料
    url(r'^profile/change/$', change_profile_view, name='change_profile'),  # 修改用户资料
    url(r'^api/docs/', include_docs_urls(title="SmallSpider_BLOG API")) # 查看api文档？？？
]


handler404 = page_not_found
handler500 = page_error

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from storm.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from storm.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
                  url(r'^baidu_verify_cB89BMWgbu\.html$', api_views.parse_seo),
                  url(r'^admin/', admin.site.urls, name="admin"),
                  # 用户
                  url(r'^accounts/', include('user.urls', namespace='accounts')),
                  # storm
                  url('', include('storm.urls', namespace='blog')),  # blog
                  # 评论
                  url(r'^comment/', include('comment.urls', namespace='comment')),  # comment
                  url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
                  # 网站地图
                  url(r'^feed/$', AllArticleRssFeed(), name='rss'),  # rss订阅
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    urlpatterns.append(url(r'^api/v1/', include(router.urls, namespace='api')))  # restframework

templates/archive.html
{% extends 'base_right.html' %}
{% load comment_tags %}

{% block title %}
    TAO丨文章归档
{% endblock title %}

{% block description %}
    <meta name="description" content="文章按照月份分类归档。"/>
{% endblock description %}

{% block keywords %}
    <meta name="keywords" content="网络爬虫工具,爬虫python,http代理,scrapy爬虫,爬虫代理ip,python为什么叫爬虫,python爬虫怎么赚钱"/>
{% endblock keywords %}

{% block body %}
    <div class="content-wrap">
        <div class="content">
            <header class="archive-header">
                <h1>
                    <i class="fa fa-folder-open"></i>&nbsp;分类：福利专区
                    <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}">
                        <i class="rss fa fa-rss"></i>
                    </a>
                </h1>
            </header>
            {% for article in page_obj %}
                <article class="excerpt">
                    <header>
                        <a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">
                            {{ article.category.name }}<i class="label-arrow"></i>
                        </a>
                        <h2>
                            <a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }}</a>
                        </h2>
                    </header>
                    <div class="focus">
                        <a target="_blank" href="/article/{{ article.slug }}">
                            <img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}"/>
                        </a>
                    </div>
                    <span class="note">{{ article.summary }}</span>
                    <p class="auth-span">
                        <span class="muted"><i class="fa fa-user"></i><a href="/author/{{ article.author }}">{{ article.author }}</a></span>
                        <span class="muted"><i class="fa fa-clock-o"></i>{{ article.create_date|date:'Y-m-d'}}</span>
                        <span class="muted"><i class="fa fa-eye"></i>{{ article.views }}浏览</span>
                        <span class="muted"><i class="fa fa-comments-o"></i><a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id article.id %}评论</a></span>
                        <span class="muted"><a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.loves }}</span>喜欢</a></span>
                    </p>
                </article>
                {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <ul>
                        {% if first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}

                        {% if left %}
                            {% if left_has_more %}
                                <li><span>...</span></li>
                            {% endif %}

                            {% for i in left %}
                                <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}

                        {% endif %}

                        <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>

                        {% if right %}
                            {% for i in right %}
                                <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}

                        {% if last %}
                            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock body %}

templates/article.html
{% extends 'base_right.html' %}
{% load blog_tags static %}

{% block title %}
    {{ object.title }}
{% endblock title %}

{% block description %}
    <meta name="description" content="{{ object.summary }}"/>
{% endblock description %}

{% block keywords %}
    <meta name="keywords" content="{% get_article_keywords object %}"/>
{% endblock keywords %}

{% block body %}
    <div class="content-wrap">
        <div class="content">
            <div class="breadcrumbs">
                <a title="返回首页" href="/"><i class="fa fa-home"></i></a><small>></small>
                <a href="/category/{{ object.category.bigcategory.slug }}">{{ object.category.bigcategory.name }}</a><small>></small>
                <a href="/category/{{ object.category.bigcategory.slug }}/{{ object.category.name|lower }}">{{ object.category.name }}</a><small>></small>
                <span class="muted">{{ object.title }}</span>
            </div>
            <header class="article-header">
                <h1 class="article-title"><a href="/article/{{ object.slug }}">{{ object.title }}</a></h1>
                <div class="meta">
                    <span id="mute-category" class="muted"><i class="fa fa-list-alt"></i><a href="category/technique/{{ object.category.name|lower }}"> {{ object.category.name }}</a></span>
                    <span class="muted"><i class="fa fa-user"></i><a href="/author/{{ object.author.name }}">{{ object.author }}</a></span>
                    <time class="muted"><i class="fa fa-clock-o"></i> {{ object.create_date|date:'y-m-d' }}</time>
                    <span class="muted"><i class="fa fa-eye"></i> {{ object.views }}浏览</span>
                    <span class="muted" style="color: #f78585!important;"><i class="fa fa-heart-o"></i> {{ object.loves }}喜欢</span>
                    <span class="muted"><i class="fa fa-comments-o"></i><a href="/article/{{ object.slug }}#respond">0评论</a></span>
                </div>
            </header>
            <article class="article-content">
                {{ article.body | safe }}
                <p>
                    转载请注明：
                    <a href="{% url 'blog:article' object.slug %}">SmallSpider</a> &raquo;
                    <a href="{% url 'blog:article' object.slug %}">{{ object.title }}</a>
                </p>

                <div class="article-social">
                    <a href="javascript:;" data-action="ding" data-id="{{ object.id }}" id="Addlike" class="action">
                        <i class="fa fa-heart-o"></i>喜欢 (<span class="count">{{ object.loves }}</span>)
                    </a>
                    <span class="or">or</span>
                    <span class="action action-share bdsharebuttonbox">
                        <i class="fa fa-share-alt"></i>分享 (<span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)
                        <div class="action-popover">
                            <div class="popover top in">
                                <div class="arrow"></div>
                                <div class="popover-content">
                                    <a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a>
                                    <a href="#" class="bds_qzone fa fa-star" data-cmd="qzone" title="分享到QQ空间"></a>
                                    <!--<a href="#" class="tencentweibo fa fa-tencent-weibo" data-cmd="tqq" title="分享到腾讯微博"></a>-->
                                    <a href="#" class="qq fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a>
                                    <a href="#" class="bds_renren fa fa-renren" data-cmd="renren" title="分享到人人网"></a>
                                    <a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin" title="分享到微信"></a>
                                    <a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a>
                                </div>
                            </div>
                        </div>
                    </span>
                </div>
            </article>

            <footer class="article-footer">
                <!--文章标签-->
                <div class="article-tags">
                    <i class="fa fa-tags"></i>
                    {% get_article_tag object.id as tags %}

                    {% for tag in tags %}
                        <a href="{% url 'blog:tag' tag.slug %}" rel="tag">{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <!--文章标签结束-->
            </footer>

            <!--推荐文章-->
            <nav class="article-nav">
                <span class="article-nav-prev">
                    <i class="fa fa-angle-double-left"></i>
                    {% get_article_previous object.id as article_previous %}
                    <a href="{% url 'blog:article' article_previous.slug %}" rel="prev">{{ article_previous.title }}</a>
                </span>
                <span class="article-nav-next">
                    {% get_article_next object.id as article_next %}
                    <a href="{% url 'blog:article' article_next.slug %}" rel="prev">{{ article_next.title }}</a>
                    <i class="fa fa-angle-double-right"></i>
                </span>
            </nav>

            <div class="related_top">
                <div class="related_posts">
                    <ul class="related_img">
                        {% get_category_article as  category_article %}

                        {% for article in category_article.article_4 %}
                            <li class="related_box">
                                <a href="{% url 'blog:article' article.slug %}" title="{{ article.title }}" target="_blank">
                                    <img src="{{ article.img_link }}" alt="{{ article.title }}"/>
                                    <br>
                                    <span class="r_title">{{ article.title }}</span>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="relates">
                        <ul>
                            {% for article in category_article.article_8 %}
                                <li>
                                    <i class="fa fa-minus"></i>
                                    <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            {% include 'comment_list.html' %}
        </div>
    </div>
{% endblock body %}

templates/base_right.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load blog_tags static %}

<!--章节目录的css-->
<style>
    .toc ul li a {
        color: #0a2e38;
    }

    .toc ul li {
        line-height: 15px;
    }
</style>

{% block right %}
    <aside class="sidebar">
        <div class="widget widget_text">
            <div class="textwidget">
                <div class="social">
                    <a href="" rel="external nofollow" title="新浪微博" target="_blank">
                        <i class="sinaweibo fa fa-weibo"></i>
                    </a>
                    <a href="" rel="external nofollow" title="腾讯微博" target="_blank">
                        <i class="tencentweibo fa fa-tencent-weibo"></i>
                    </a>
                    <a href="" rel="external nofollow" title="微信" target="_blank">
                        <i class="weixins fa fa-weixin"></i>
                    </a>
                    <!--多出来的标签 ==> 可以做微信扫码添加-->
                    <!--<a class="weixin">
                    <div class="weixin-popover">
                        <div class="popover bottom in">
                            <div class="arrow"></div>
                            <div class="popover-title"></div>
                            <div class="popover-content"><img src="{% static 'images/get_1.png' %}"></div>
                        </div>
                    </div>
                </a>-->
                    <!--<a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=mail@stormsha.com" rel="external nofollow" title="Email" target="_blank">
                        <i class="email fa fa-envelope-o"></i>
		    </a>-->
                    <a href="/feed/" rel="external nofollow" target="_blank" title="订阅本站">
                        <i class="rss fa fa-rss"></i>
                    </a>
                </div>
            </div>
        </div>
        
	<!--章节目录-->
	{% if article %}
	    <div class="widget widget_text">
	        <div class="title">
	            <h2>章节目录</h2>
	        </div>
	        <div class="article-content" style="line-height: 0px;">
		    {{ article.toc | safe }}
	        </div>
	    </div>
	{% endif %}
        
	<!--gif动画-->
	<div class="widget widget_text">
	    <div class="textwidget">
	        <!--<a href="/"><img style="width:100%" src="{% static 'images/get_2.gif' %}"/></a>-->
		<a href="/"><img style="width:100%" src="{% static 'images/it_pboy' %}"/></a>
	    </div>
	</div>

	<!--热门专题-->
        <div class="widget widget_metaslider_widget">
            <div class="title">
                <h2>热门专题</h2>
            </div>
            <!-- meta slider -->
            <div style="width: 100%;" class="metaslider metaslider-nivo metaslider-2698 ml-slider meta-slider">
                <div id="metaslider_container_2698">
                    <div class='slider-wrapper theme-bar'>
                        <div class='ribbon'></div>
                        <div id='metaslider_2698' class='nivoSlider'>
                            {% get_carousel_right as carousels %}

                            {% for carousel in carousels %}
                                <a href="{{ carousel.url }}" target="_blank">
                                    <img src="{{ carousel.img_url }}" height="300" width="320" data-title="{{ carousel.content }}" title="{{ carousel.title }}" alt="{{ carousel.title }}" class="slider-2698 slide-1720"/>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--热门专题结束-->

                <script type="text/javascript">
                    var metaslider_2698 = function ($) {
                        $('#metaslider_2698').nivoSlider({
                            boxCols: 7,
                            boxRows: 5,
                            pauseTime: 3000,
                            effect: "random",
                            controlNav: false,
                            directionNav: true,
                            pauseOnHover: true,
                            animSpeed: 600,
                            prevText: "&lt;",
                            nextText: "&gt;",
                            slices: 15,
                            manualAdvance: false
                        });
                    };
                    var timer_metaslider_2698 = function () {
                        var slider = !window.jQuery ? window.setTimeout(timer_metaslider_2698, 100) : !jQuery.isReady ?
                            window.setTimeout(timer_metaslider_2698, 1) : metaslider_2698(window.jQuery);
                    };
                    timer_metaslider_2698();
                </script>
            </div>
            <!--// meta slider-->
        </div>
	
	<!--广告位
        <div class="widget widget_text">
            <div class="textwidget">
		<<a href="/"><img style="width:100%" src="{% static 'images/get_2.gif' %}"/></a>
		<a href="/"><img style="width:100%" src="{% static 'images/it_pboy' %}"/></a>
            </div>
        </div>
        广告位结束-->

        <!--文章归档-->
        <div class="widget widget_archive">
            <div class="title">
                <h2>文章归档</h2>
            </div>
            {% get_data_date as data_date %}
            <ul>
                {% if data_date %}
                    {% for date in data_date %}
                        <li>
                            <a href='{% url 'blog:date' date|date:'Y' date|date:'m' %}'>{{ date|date:'Y-m' }}</a>
                        </li>
                    {% endfor %}
                {% else %}
                    <div>暂未发表相关文章</div>
                {% endif %}
            </ul>
        </div>
        <!--文章归档结束-->

        <!--猜你喜欢-->
        <div class="widget d_postlist">
            <div class="title">
                <h2>猜你喜欢</h2>
            </div>
            <ul>
                {% get_article_list '-views' 6 as hot_tag %} <!--这里是发送的sort-->
                {% for hot in hot_tag %}
                    <li>
                        <a href="/article/{{ hot.slug }} " title="{{ hot.title }}">
                            <span class="thumbnail">
                                <img src="{{ hot.img_link }}" alt="{{ hot.title }}"/>
                            </span>
                            <span class="text">{{ hot.title }}</span>&nbsp;
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                            <span class="muted">{{ hot.create_date|date:'Y-m-d' }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            <span class="muted">{{ hot.views }}浏览</span>
                            <!-- <span class="muted">{{ hot.loves }}喜欢</span> -->
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!--猜你喜欢结束-->

        <!--标签云-->
        <div class="widget d_tag">
            <div class="title">
                <h2>标签云</h2>
            </div>
            <div class="d_tags">
                {% get_tag_list as tags %}
                {% for tag in tags %}
                    <a title="{{ tag.total_num }}个话题" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}({{ tag.total_num }})</a>
                {% endfor %}
            </div>
        </div>
        <!--标签云结束-->

        <!--友情链接-->
        <div class="widget widget_links">
            <div class="title">
                <h2>友情链接</h2>
            </div>
            {% get_friends as friends %}
            <ul class='xoxo blogroll'>
                {% if friends %}
                    {% for friend in friends %}
                        <li>
                            <a href="{{ friend.link }}" target="_blank">{{ friend.name }}</a>
                        </li>
                    {% endfor %}
                {% else %}
                    <div>&nbsp;&nbsp;暂无友链，欢迎来战！&nbsp;&nbsp;</div>
                {% endif %}
            </ul>
        </div>
        <!--友情链接结束-->

        <!--
        精品推荐
        <div class="widget widget_text">
            <div class="title">
                <h2>精品推荐</h2>
            </div>
            <div class="text widget">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;广告位诚邀加盟
            </div>
        </div>
        精品推荐结束

        <div class="widget widget_text">
        </div>
        -->
    </aside>
{% endblock right %}

templates/content.html
{% extends 'base_right.html' %}
{% load comment_tags blog_tags %}

{% block description %}
    <meta name="description" content="{% get_title category as c %}{{ c.description }}"/>
{% endblock description %}

{% block keywords %}
    <meta name="keywords" content="{% get_title category as c %}{{ c.keywords }}"/>
{% endblock keywords %}

{% block title %}
    {% get_title category as c %}TAO丨{{ c.name }}
{% endblock title %}

{% block body %}
    <div class="content-wrap">
        <div class="content">
            <header class="archive-header">
                <h1>
                    <i class="fa fa-folder-open"></i> &nbsp;分类：福利专区
                    <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}">
                        <i class="rss fa fa-rss"></i>
                    </a>
                </h1>
            </header>
            {% for article in page_obj %}
                <article class="excerpt">
                    <header>
                        <a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}
                            <i class="label-arrow"></i>
                        </a>
                        <h2>
                            <a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a>
                        </h2>
                    </header>
                    <div class="focus">
                        <a target="_blank" href="/article/{{ article.slug }}">
                            <img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}"/>
                        </a>
                    </div>
                    <span class="note"> {{ article.summary }}</span>
                    <p class="auth-span">
                        <span class="muted"><i class="fa fa-user"></i><a href="/author/{{ article.author }}">{{ article.author }}</a></span>
                        <span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d'}}</span>
                        <span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>
                        <span class="muted"><i class="fa fa-comments-o"></i><a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id article.id %}评论</a></span>
                        <span class="muted"><a href="javascript:;" data-action="ding" data-id="{{ article.id }}" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.loves }}</span>喜欢</a></span>
                    </p>
                </article>
                {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
            {% endfor %}

            {% if is_paginated %}
                <div class="pagination">
                    <ul>
                        {% if first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}

                        {% if left %}
                            {% if left_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                            {% for i in left %}
                                <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}

                        <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                        {% if right %}
                            {% for i in right %}
                                <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}

                            {% if right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}

                        {% if last %}
                            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                        {% endif %}

                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock body %}

templates/link.html
{%extends 'base.html' %}
{% load blog_tags %}
{%block title%}TAO丨添加友链{%endblock title%}

{%block body%}
<div class="pagewrapper clearfix">
    <header class="pageheader clearfix">
        <h1 class="pull-left">
            <a href="https://cuiqingcai.com/link">申请友链</a>
        </h1>
        <div class="pull-right">
            <!-- 百度分享 -->
            <span class="action action-share bdsharebuttonbox">
                <i class="fa fa-share-alt"></i>分享 (<span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)
                <div class="action-popover">
                    <div class="popover top in">
                        <div class="arrow"></div>
                        <div class="popover-content">
                            <a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_qzone fa fa-star" data-cmd="qzone" title="分享到QQ空间"></a>
                            <!--<a href="#" class="tencentweibo fa fa-tencent-weibo" data-cmd="tqq" title="分享到腾讯微博"></a>-->
                            <a href="#" class="qq fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a>
                            <a href="#" class="bds_renren fa fa-renren" data-cmd="renren" title="分享到人人网"></a>
                            <a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin" title="分享到微信"></a>
                            <a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a>
                        </div>
                    </div>
                </div>
            </span>
        </div>
    </header>
    <div class="article-content">
        <!-- link -->
        <div class="friend-link">
            <h2 style="text-align: center;">友链互添</h2>
            <h3 style="text-align: center;">友链互添标准</h3>
            <blockquote style="text-align: center; line-height: 25px;">
                <p>贵站必须有二十篇以上技术类别原创文章</p>
                <p>贵站如两个月没有更新本站则会取消友链</p>
                <p>贵站如一个月无法访问本站则会取消友链</p>
                <p>贵站如取消本站友链本站则取消贵站友链</p>
                <p>贵站如有访问或地址更新请及时通知本站</p>
            </blockquote>
            <h3 class="icon-contact" style="text-align: center;">友链互添方式</h3>
            <!--<div class="icon-contact" style="text-align: center;">本站名称：smallspider</div>-->
            <div class="icon-contact" style="text-align: center;">本站地址：<a
                    href="http://stormsha.com">http://47.103.202.63:1996/</a></div>
            <h4 class="icon-contact" style="text-align: center;">同步添加方式</h4>
            <!--<div class="icon-contact" style="text-align: center;">1. 私信官方新浪微博 @<a href="https://weibo.com/"
                    target="_blank">SmallSpider</a>，附上贵站名称及地址，如符合要求，我会与你取得联系并互相添加友链。</div>-->
            <div class="icon-contact" style="text-align: center;">
                邮件至 small.spider.p@gmail.com，附上贵站名称及地址，如符合要求，我会与你取得联系并互相添加友链。
            </div>
            <h4 class="icon-contact" style="text-align: center;">异步添加方式</h4>
            <div class="icon-contact" style="text-align: center;">1.
                贵站添加本站友链后，在本页面或者给我留言页面留言，附上贵站名称及地址，我会回复评论，如贵站符合要求，添加贵站友链。</div>
        </div>
        <!-- end link -->
    </div>
</div>
{%endblock body%}